import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} bg-[#E3EAEF] flex flex-col h-full`}>
        <Navbar />
        <main className="max-w-[1400px] m-2 w-full rounded-[4px] bg-white border border-[#D8DFE6] mx-auto h-full overflow-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
